services:
  backend:
    build: ./backend
    container_name: bottle
    expose:
      - "5000"
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    networks:
      - schematic
    restart: unless-stopped

  web:
    build: ./web
    container_name: nginx
    ports:
      - "5633:5633"
    networks:
      - schematic
    restart: unless-stopped

networks:
  schematic:
    driver: bridge
