services:
  nutrition:
    build: ./services/nutrition
    container_name: nutrition
    expose:
      - "5000"
    volumes:
      - ./services/nutrition:/app
    networks:
      - schematic
    restart: unless-stopped

  web:
    build: ./web
    container_name: web
    ports:
      - "80:80"
    networks:
      - schematic
    restart: unless-stopped

networks:
  schematic:
    driver: bridge
