services:
  backend:
    build: ./backend
    container_name: bottle
    expose:
      - "5000"
    volumes:
      - ./backend:/app
    networks:
      - schematic
    restart: unless-stopped

  web:
    build: ./web
    container_name: nginx
    ports:
      - "80:80"
    networks:
      - schematic
    restart: unless-stopped

networks:
  schematic:
    driver: bridge
