services:
  bottle:
    build: ./backend
    ports:
      - "5000"
    volumes:
      - ./backend:/app
    environment:
      - ENV=development

  nginx:
    build: ./frontend
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
