services:
  backend:
    build: ./backend
    container_name: bottle
    expose:
      - "5000"
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    networks:
      - nutriplanner
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: nginx
    ports:
      - "5633:5633"
    networks:
      - nutriplanner
    restart: unless-stopped

networks:
  nutriplanner:
    driver: bridge
