repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.8 # Latest stable version
    hooks:
      - id: ruff
        args: [--fix]  # Optional: Automatically fixes issues

  - repo: https://github.com/psf/black
    rev: 25.1.0  # Latest stable version
    hooks:
      - id: black

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0  # Latest stable version
    hooks:
      - id: isort
        args: ["--profile", "black"]  # Ensures compatibility with Black

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0  # Latest version
    hooks:
      - id: trailing-whitespace  # Removes unnecessary trailing whitespace
      - id: end-of-file-fixer  # Ensures a newline at the end of each file
